[package]
name = "euleretal"
version = "0.1.0"
authors = ["quadruple-output <57874618+quadruple-output@users.noreply.github.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.4", features = ["dynamic", "x11", "png", "bevy_wgpu"] }
bevy_egui = "0.1.3"
decorum = "0.3.1"
egui = "0.8"
flexi_logger = "0.17"
log = "0.4"
